# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate ssh-agent-client-rs

Name:           rust-ssh-agent-client-rs
Version:        1.0.0
Release:        %autorelease
Summary:        Pure rust implementation of the ssh-agent protocol

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/ssh-agent-client-rs
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          ssh-agent-client-rs-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure rust implementation of the ssh-agent protocol. It can be used to
write clients that interact with the ssh agent.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
